package HighSchool.Pojos;
// Generated 09/02/2015 04:05:06 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CourseHasStudent generated by hbm2java
 */
@Entity
@Table(name="Course_has_Student"
    ,catalog="highschool"
)
public class CourseHasStudent  implements java.io.Serializable {


     private CourseHasStudentId id;
     private Course course;
     private Student student;
     private String parcial1;
     private String parcial2;
     private String parcial3;
     private String final_;

    public CourseHasStudent() {
    }

	
    public CourseHasStudent(CourseHasStudentId id, Course course, Student student) {
        this.id = id;
        this.course = course;
        this.student = student;
    }
    public CourseHasStudent(CourseHasStudentId id, Course course, Student student, String parcial1, String parcial2, String parcial3, String final_) {
       this.id = id;
       this.course = course;
       this.student = student;
       this.parcial1 = parcial1;
       this.parcial2 = parcial2;
       this.parcial3 = parcial3;
       this.final_ = final_;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="courseIdCourse", column=@Column(name="Course_idCourse", nullable=false) ), 
        @AttributeOverride(name="studentRegNum", column=@Column(name="Student_regNum", nullable=false) ) } )
    public CourseHasStudentId getId() {
        return this.id;
    }
    
    public void setId(CourseHasStudentId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Course_idCourse", nullable=false, insertable=false, updatable=false)
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Student_regNum", nullable=false, insertable=false, updatable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="parcial1", length=16777215)
    public String getParcial1() {
        return this.parcial1;
    }
    
    public void setParcial1(String parcial1) {
        this.parcial1 = parcial1;
    }

    
    @Column(name="parcial2", length=16777215)
    public String getParcial2() {
        return this.parcial2;
    }
    
    public void setParcial2(String parcial2) {
        this.parcial2 = parcial2;
    }

    
    @Column(name="parcial3", length=16777215)
    public String getParcial3() {
        return this.parcial3;
    }
    
    public void setParcial3(String parcial3) {
        this.parcial3 = parcial3;
    }

    
    @Column(name="final", length=16777215)
    public String getFinal_() {
        return this.final_;
    }
    
    public void setFinal_(String final_) {
        this.final_ = final_;
    }




}


