package HighSchool.Pojos;
// Generated 09/02/2015 04:05:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name="Course"
    ,catalog="highschool"
)
public class Course  implements java.io.Serializable {


     private Integer idCourse;
     private String course;
     private String teacherLastName;
     private String teacherFirstName;
     private Integer hoursWeek;
     private Set<TeacherHasCourse> teacherHasCourses = new HashSet<TeacherHasCourse>(0);
     private Set<CourseHasStudent> courseHasStudents = new HashSet<CourseHasStudent>(0);
     private Set<Schedule> schedules = new HashSet<Schedule>(0);

    public Course() {
    }
    
    public Course(String course,Integer hoursWeek){
        this.course = course;
        this.hoursWeek = hoursWeek;
    }

    public Course(String course, String teacherLastName, String teacherFirstName, Integer hoursWeek, Set<TeacherHasCourse> teacherHasCourses, Set<CourseHasStudent> courseHasStudents, Set<Schedule> schedules) {
       this.course = course;
       this.teacherLastName = teacherLastName;
       this.teacherFirstName = teacherFirstName;
       this.hoursWeek = hoursWeek;
       this.teacherHasCourses = teacherHasCourses;
       this.courseHasStudents = courseHasStudents;
       this.schedules = schedules;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCourse", unique=true, nullable=false)
    public Integer getIdCourse() {
        return this.idCourse;
    }
    
    public void setIdCourse(Integer idCourse) {
        this.idCourse = idCourse;
    }

    
    @Column(name="course", length=45)
    public String getCourse() {
        return this.course;
    }
    
    public void setCourse(String course) {
        this.course = course;
    }

    
    @Column(name="teacherLastName", length=45)
    public String getTeacherLastName() {
        return this.teacherLastName;
    }
    
    public void setTeacherLastName(String teacherLastName) {
        this.teacherLastName = teacherLastName;
    }

    
    @Column(name="teacherFirstName", length=45)
    public String getTeacherFirstName() {
        return this.teacherFirstName;
    }
    
    public void setTeacherFirstName(String teacherFirstName) {
        this.teacherFirstName = teacherFirstName;
    }

    
    @Column(name="hoursWeek")
    public Integer getHoursWeek() {
        return this.hoursWeek;
    }
    
    public void setHoursWeek(Integer hoursWeek) {
        this.hoursWeek = hoursWeek;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="course")
    public Set<TeacherHasCourse> getTeacherHasCourses() {
        return this.teacherHasCourses;
    }
    
    public void setTeacherHasCourses(Set<TeacherHasCourse> teacherHasCourses) {
        this.teacherHasCourses = teacherHasCourses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="course")
    public Set<CourseHasStudent> getCourseHasStudents() {
        return this.courseHasStudents;
    }
    
    public void setCourseHasStudents(Set<CourseHasStudent> courseHasStudents) {
        this.courseHasStudents = courseHasStudents;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="course")
    public Set<Schedule> getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set<Schedule> schedules) {
        this.schedules = schedules;
    }




}


