package HighSchool.Pojos;
// Generated 09/02/2015 04:05:06 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CourseHasStudentId generated by hbm2java
 */
@Embeddable
public class CourseHasStudentId  implements java.io.Serializable {


     private int courseIdCourse;
     private int studentRegNum;

    public CourseHasStudentId() {
    }

    public CourseHasStudentId(int courseIdCourse, int studentRegNum) {
       this.courseIdCourse = courseIdCourse;
       this.studentRegNum = studentRegNum;
    }
   


    @Column(name="Course_idCourse", nullable=false)
    public int getCourseIdCourse() {
        return this.courseIdCourse;
    }
    
    public void setCourseIdCourse(int courseIdCourse) {
        this.courseIdCourse = courseIdCourse;
    }


    @Column(name="Student_regNum", nullable=false)
    public int getStudentRegNum() {
        return this.studentRegNum;
    }
    
    public void setStudentRegNum(int studentRegNum) {
        this.studentRegNum = studentRegNum;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CourseHasStudentId) ) return false;
		 CourseHasStudentId castOther = ( CourseHasStudentId ) other; 
         
		 return (this.getCourseIdCourse()==castOther.getCourseIdCourse())
 && (this.getStudentRegNum()==castOther.getStudentRegNum());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCourseIdCourse();
         result = 37 * result + this.getStudentRegNum();
         return result;
   }   


}


