package HighSchool.Pojos;
// Generated 09/02/2015 04:05:06 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hour generated by hbm2java
 */
@Entity
@Table(name="Hour"
    ,catalog="highschool"
)
public class Hour  implements java.io.Serializable {


     private Integer idHour;
     private Date startHour;
     private Date finishHour;
     private Set<Schedule> schedules = new HashSet<Schedule>(0);

    public Hour() {
    }

    public Hour(Date startHour, Date finishHour, Set<Schedule> schedules) {
       this.startHour = startHour;
       this.finishHour = finishHour;
       this.schedules = schedules;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idHour", unique=true, nullable=false)
    public Integer getIdHour() {
        return this.idHour;
    }
    
    public void setIdHour(Integer idHour) {
        this.idHour = idHour;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="startHour", length=8)
    public Date getStartHour() {
        return this.startHour;
    }
    
    public void setStartHour(Date startHour) {
        this.startHour = startHour;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="finishHour", length=8)
    public Date getFinishHour() {
        return this.finishHour;
    }
    
    public void setFinishHour(Date finishHour) {
        this.finishHour = finishHour;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hour")
    public Set<Schedule> getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set<Schedule> schedules) {
        this.schedules = schedules;
    }




}


