package HighSchool.Pojos;
// Generated 09/02/2015 04:05:06 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ScheduleId generated by hbm2java
 */
@Embeddable
public class ScheduleId  implements java.io.Serializable {


     private int idWeekDay;
     private int idHour;
     private int idCourse;

    public ScheduleId() {
    }

    public ScheduleId(int idWeekDay, int idHour, int idCourse) {
       this.idWeekDay = idWeekDay;
       this.idHour = idHour;
       this.idCourse = idCourse;
    }
   


    @Column(name="idWeekDay", nullable=false)
    public int getIdWeekDay() {
        return this.idWeekDay;
    }
    
    public void setIdWeekDay(int idWeekDay) {
        this.idWeekDay = idWeekDay;
    }


    @Column(name="idHour", nullable=false)
    public int getIdHour() {
        return this.idHour;
    }
    
    public void setIdHour(int idHour) {
        this.idHour = idHour;
    }


    @Column(name="idCourse", nullable=false)
    public int getIdCourse() {
        return this.idCourse;
    }
    
    public void setIdCourse(int idCourse) {
        this.idCourse = idCourse;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ScheduleId) ) return false;
		 ScheduleId castOther = ( ScheduleId ) other; 
         
		 return (this.getIdWeekDay()==castOther.getIdWeekDay())
 && (this.getIdHour()==castOther.getIdHour())
 && (this.getIdCourse()==castOther.getIdCourse());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdWeekDay();
         result = 37 * result + this.getIdHour();
         result = 37 * result + this.getIdCourse();
         return result;
   }   


}


