package HighSchool.Pojos;
// Generated 09/02/2015 04:05:06 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name="Schedule"
    ,catalog="highschool"
)
public class Schedule  implements java.io.Serializable {


     private ScheduleId id;
     private Course course;
     private Hour hour;
     private WeekDay weekDay;

    public Schedule() {
    }

    public Schedule(ScheduleId id, Course course, Hour hour, WeekDay weekDay) {
       this.id = id;
       this.course = course;
       this.hour = hour;
       this.weekDay = weekDay;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idWeekDay", column=@Column(name="idWeekDay", nullable=false) ), 
        @AttributeOverride(name="idHour", column=@Column(name="idHour", nullable=false) ), 
        @AttributeOverride(name="idCourse", column=@Column(name="idCourse", nullable=false) ) } )
    public ScheduleId getId() {
        return this.id;
    }
    
    public void setId(ScheduleId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCourse", nullable=false, insertable=false, updatable=false)
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idHour", nullable=false, insertable=false, updatable=false)
    public Hour getHour() {
        return this.hour;
    }
    
    public void setHour(Hour hour) {
        this.hour = hour;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idWeekDay", nullable=false, insertable=false, updatable=false)
    public WeekDay getWeekDay() {
        return this.weekDay;
    }
    
    public void setWeekDay(WeekDay weekDay) {
        this.weekDay = weekDay;
    }




}


