package HighSchool.Pojos;
// Generated 09/02/2015 04:05:06 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TeacherHasCourse generated by hbm2java
 */
@Entity
@Table(name="Teacher_has_Course"
    ,catalog="highschool"
)
public class TeacherHasCourse  implements java.io.Serializable {


     private Integer id;
     private Course course;
     private Teacher teacher;

    public TeacherHasCourse() {
    }

    public TeacherHasCourse(Course course, Teacher teacher) {
       this.course = course;
       this.teacher = teacher;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCourse")
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTeacher")
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }




}


