package HighSchool.Pojos;
// Generated 09/02/2015 04:05:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * WeekDay generated by hbm2java
 */
@Entity
@Table(name="WeekDay"
    ,catalog="highschool"
)
public class WeekDay  implements java.io.Serializable {


     private Integer idWeekDay;
     private String dayName;
     private Set<Schedule> schedules = new HashSet<Schedule>(0);

    public WeekDay() {
    }

    public WeekDay(String dayName, Set<Schedule> schedules) {
       this.dayName = dayName;
       this.schedules = schedules;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idWeekDay", unique=true, nullable=false)
    public Integer getIdWeekDay() {
        return this.idWeekDay;
    }
    
    public void setIdWeekDay(Integer idWeekDay) {
        this.idWeekDay = idWeekDay;
    }

    
    @Column(name="dayName", length=45)
    public String getDayName() {
        return this.dayName;
    }
    
    public void setDayName(String dayName) {
        this.dayName = dayName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="weekDay")
    public Set<Schedule> getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set<Schedule> schedules) {
        this.schedules = schedules;
    }




}


