package UserService;

import Model.Photo;
import Model.User;
import java.util.ArrayList;
import javax.annotation.Resource;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import java.util.concurrent.atomic.AtomicInteger;

/**
 *
 * @author german
 */
@RestController
public class UserDaoController  {
    
    @Resource
    private UserDao userDao;
    
    private AtomicInteger userCounter = new AtomicInteger();
    
    /**
     *get all users from user's list
     * @return a list of user
     */
    @RequestMapping("/getallusers")
    
    public ArrayList<User> getAllUsers() {
       return userDao.getAllUsers();
    }
    
    /**
     * add a new user to user's list, the id is autogenerated
     * @param name name of the new user
     * @param password password of the new user
     */
    @RequestMapping("/adduser")
    
    public void addUser(@RequestParam(value="name")String name,
        @RequestParam(value="password")String password) {
        
          
        User user = new User(userCounter.incrementAndGet(),name,password);        
        userDao.addUser(user);
    }
    
    /**
     *deleted the user with the given id
     * @param id user's id
     */
    @RequestMapping("/deleteuser")
    public void deleteUser(@RequestParam(value="id")int id) {
        userDao.deleteUser(id);
    }
    
    /**
     *update the name of a given user
     * @param id user's id
     * @param name user new name
     */
    @RequestMapping("/update")
    public void updateUser(@RequestParam(value="id") int id,
                            @RequestParam(value="name")String name) {
        userDao.updateUser(id,name);
    }
    
    /**
     *add a new photo to user's album
     * @param id user's id
     * @param uri path to user's album
     */
    @RequestMapping("/addphoto")
    public void addPhoto(@RequestParam(value="id") int id,
            @RequestParam(value="uri")String uri) {
      
        userDao.addPhoto(id,uri);
    }
    
    /**
     * add a friend relationship to a given user
     * @param idUser user's id
     * @param idFriend user's new friend id
     */
    @RequestMapping("/addfriend")
    public void addFriend(@RequestParam(value="iduser") int idUser,
            @RequestParam(value="idfriend")int idFriend) {
      
        userDao.addFriend(idUser,idFriend);
    }
    
    /**
     *add a like to given user pic
     * @param id of the owner of the picture
     * @param idPhoto of the picture liked
     */
    @RequestMapping("/likePic")
    public void likeToUserPhoto(@RequestParam(value="id")int id, 
            @RequestParam(value="idpic")int idPhoto) {
            userDao.likeToUserPhoto(id, idPhoto);
    }
    
    
    

}
