package Booking.Pojos;
// Generated 07/02/2015 00:20:26 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="CLIENT"
    ,schema="PUBLIC"
    ,catalog="PUBLIC"
)
public class Client  implements java.io.Serializable {


     private Integer idclient;
     private String name;
     private String lastname;
     @JsonIgnore
     private Set<Meetting> meettings = new HashSet<Meetting>(0);

    public Client() {
    }

    public Client(String name, String lastname) {
       this.name = name;
       this.lastname = lastname;
       this.meettings = meettings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDCLIENT", unique=true, nullable=false)
    public Integer getIdclient() {
        return this.idclient;
    }
    
    public void setIdclient(Integer idclient) {
        this.idclient = idclient;
    }

    
    @Column(name="NAME", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="LASTNAME", length=45)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set<Meetting> getMeettings() {
        return this.meettings;
    }
    
    public void setMeettings(Set<Meetting> meettings) {
        this.meettings = meettings;
    }




}


