package Booking.Pojos;
// Generated 07/02/2015 00:20:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Meetting generated by hbm2java
 */
@Entity
@Table(name="MEETTING"
    ,schema="PUBLIC"
    ,catalog="PUBLIC"
)
public class Meetting  implements java.io.Serializable {


     private Integer idmeetting;
     private Client client;
     private Room room;
     private Date startmeeting;
     private Date finishmeeting;
     private boolean status;

    public Meetting() {
    }

    public Meetting(Client client, Room room, Date startmeeting, Date finishmeeting) {
       this.client = client;
       this.room = room;
       this.startmeeting = startmeeting;
       this.finishmeeting = finishmeeting;
       this.status = true;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDMEETTING", unique=true, nullable=false)
    public Integer getIdmeetting() {
        return this.idmeetting;
    }
    
    public void setIdmeetting(Integer idmeetting) {
        this.idmeetting = idmeetting;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCLIENT")
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ROOMNUM")
    public Room getRoom() {
        return this.room;
    }
    
    public void setRoom(Room room) {
        this.room = room;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="STARTMEETING", length=26)
    public Date getStartmeeting() {
        return this.startmeeting;
    }
    
    public void setStartmeeting(Date startmeeting) {
        this.startmeeting = startmeeting;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FINISHMEETING", length=26)
    public Date getFinishmeeting() {
        return this.finishmeeting;
    }
    
    public void setFinishmeeting(Date finishmeeting) {
        this.finishmeeting = finishmeeting;
    }




}


