package Booking.Pojos;
// Generated 07/02/2015 00:20:26 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name="ROOM"
    ,schema="PUBLIC"
    ,catalog="PUBLIC"
)
public class Room  implements java.io.Serializable {


     private Integer roomnum;
     private Integer floor;
     private Integer capacity;
     private Double price;
     @JsonIgnore
     private Set<Meetting> meettings = new HashSet<Meetting>(0);

    public Room() {
    }

    public Room(Integer floor, Integer capacity) {
       this.floor = floor;
       this.capacity = capacity;
       this.price = price;
       this.meettings = meettings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ROOMNUM", unique=true, nullable=false)
    public Integer getRoomnum() {
        return this.roomnum;
    }
    
    public void setRoomnum(Integer roomnum) {
        this.roomnum = roomnum;
    }

    
    @Column(name="FLOOR")
    public Integer getFloor() {
        return this.floor;
    }
    
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    
    @Column(name="CAPACITY")
    public Integer getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    
    @Column(name="PRICE", precision=64, scale=0)
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="room")
    public Set<Meetting> getMeettings() {
        return this.meettings;
    }
    
    public void setMeettings(Set<Meetting> meettings) {
        this.meettings = meettings;
    }




}


